<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <LineageInstrument>false</LineageInstrument>
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <LineageVersion>0.1.0</LineageVersion>
    <Version>$(LineageVersion)</Version>
  </PropertyGroup>
</Project>
