<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>Lineage.Instrumentation</RootNamespace>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Build.Utilities.Core" Version="17.11.4" />
    <PackageReference Include="Mono.Cecil" Version="0.11.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lineage.Runtime\Lineage.Runtime.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="_orig_MethodWeaver.cs" />
    <Compile Remove="_patched_MethodWeaver.cs" />
  </ItemGroup>

</Project>
